[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
"chainlink-brownie-contracts/=lib/chainlink-brownie-contracts/",
"@foundry-devops/src=lib/foundry-devops/src/",
"@solmate/tokens=lib/solmate/src/tokens/",
"ds-test/=lib/forge-std/lib/ds-test/src/",
"forge-std/=lib/forge-std/src/"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
